### ISSUE TITLE
`here` link is dead in IPS-DEV *Python*

### ISSUE THREAD

**Issue by lopagela** [dubrayn/dubrayn.github.io#3]
In the Python page, IPS-DEV, the `here` page is dead, `nginx` returns a 404: https://artifex.org/~hblanks/talks/2011/pep20_by_example.pdf
https://github.com/dubrayn/dubrayn.github.io/blob/397a7993b30a81c656a4d47abfe9a50a9c162068/IPS-DEV/python.html#L84

**Comment by dubrayn** [comment]
fixed, thanks !
